### ISSUE TITLE
`llvm-config --libs spirv` does not return LLVMSPIRVLib

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/SPIRV-LLVM#41]
I am not sure whether or not this is a real issue, but target `spirv` of `llvm-config` returns `spirvinfo`, `spirvdesc` and `spirvcodegen` but not `spirvlib`. Is it per design or was it just forgotten?

**Comment by yxsamliu** [comment]
For now the spirv target does not use spirvlib.

**Comment by pierremoreau** [comment]
Oh, I thought `spirv` was only a "fake" target to include all related SPIR-V (sub-)targets.

I probably also went the wrong path when trying to generate SPIR-V from some code, as I think I used the frontend rather than the backend (using `clang::EmitSPIRVAction` and then `llvm::WriteSPIRV`, which is in `LLVMSPIRVLib`).

**Comment by yxsamliu** [comment]
I did not try using clang with spirv target yet. For now I use llc to test it, e.g.
llc -march=spir empty.bc

currently it still misses basic stuff.

**Comment by pierremoreau** [comment]
Well, I'm still at integrating really basic stuff, so it has enough stuff in for now. :-) Except that `DataLayout::getSmallestLegalIntType()` always return a `nullptr`, but that's a separate issue that I'll investigate.

**Comment by yxsamliu** [comment]
I've fixed that and will commit the change. now I am implementing LowerFormalArguments.

**Comment by pierremoreau** [comment]
I tried your patch but still have the issue. None of the `Desc` fed to DataLayout contains an 'n' attribute, so `LegalIntWidths` remains empty. Maybe LowerFormalArguments is needed? I opened #42 to stop misusing this one.

**Comment by yxsamliu** [comment]
Sorry I thought my commit fixed that but it seems missing something else.

**Comment by pierremoreau** [comment]
Just a small bump on this one to make sure I understand correctly, and we can close this one. Is the `spirv` target of `llvm-config` for using the SPIR-V backend of SPIRV-LLVM? And, by using `clang::EmitSPIRVAction`, am I using the frontend or the backend?

By the way, what's the status of the backend?

**Comment by yxsamliu** [comment]
spirv backend of llvm-config is for SPIR-V backend.
clang::EmitSPIRVAction uses the translator, not the backend.

Sorry I did not work on the backend recently due to lack of resources. Any help are welcome.

**Comment by pierremoreau** [comment]
Oh, ok! How do I call the backend then?

No problem. I won't have time before April for sure, but then, maybe… Do you have any pointers on where to start playing, some easy beginner tasks?

(Closing as _not a bug_, just me misunderstanding things)

**Comment by yxsamliu** [comment]
You need to use llc to use the spirv backend.
llc -mcpu=spir input.bc

We should start with simple bc, e.g. an empty function, then integer types and instructions.

https://github.com/KhronosGroup/SPIRV-LLVM/blob/spirv-backend/lib/Target/SPIRV/SPIRVFrameLowering.h needs to be updated to handle stack frames.

**Comment by pierremoreau** [comment]
Ok, thank you the information. I'll see what I can do when I find some time.
